### ISSUE TITLE
Question: what is this

### ISSUE THREAD

**Issue by JonnyboyTheboy** [Dot-Stuff/Dot-Engine#12]
what is this mod

**Comment by DotWith** [comment]
This engine adds full modding support, customizable control schemes, etc. The upcoming things are mobile, multiplayer, translations, and fixed Linux support.

Were always looking into making this engine the most simplistic but not be bloated. _Cough.. Cough.. KadeEngine._ Anyways you can always join our [discord](https://www.discord.gg/u9B7qkkhtM). Our community isn't toxic, infect help each other.
