### ISSUE TITLE
flxanimate crashes the game

### ISSUE THREAD

**Issue by ACrazyTown** [Dot-Stuff/Dot-Engine#2]
happens on booting up week 7 story mode
is this supposed to happen?

the issue happens in FlxSymbol
and it's something along the lines of "can't read property of undefined swagFrame.E"

**Comment by DotWith** [comment]
Yea, its line 39 from **FlxAnimate.hx**
It wont load the TextFile for some reason.

**Comment by DotWith** [comment]
Just comment out that code for tankman in cutscene

**Comment by ACrazyTown** [comment]
> Yea, its line 39 from **FlxAnimate.hx** It wont load the TextFile for some reason.

For me it was something from FlxSymbol not being able to read the E property, are you sure it's FlxAnimate?
But I'd like to figure it out

**Comment by ACrazyTown** [comment]
i fixed it lmao

you just have to add an if statement that checks if swagframe is null before iterating over it's elements
