### ISSUE TITLE
Bug Report:  Whenever you bind controls, all the controls stop working

### ISSUE THREAD

**Issue by gaminbottomtext** [Dot-Stuff/Dot-Engine#6]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below. Windows

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Go to the controls menu, and then rebind anything. all other controls stop

**Comment by DotWith** [comment]
This bug hasn't been fixed yet. A solution for now is to delete your ninjamuffin99 folder in your AppData/Roaming

**Comment by gaminbottomtext** [comment]
Yea becuz playersettings always says it loads the key data { } unlike the ng build where it has info inside the {}

**Comment by DotWith** [comment]
https://github.com/Dot-Stuff/Dot-Engine/blob/b4623d8619c084aa1d796930d956326f48fc9c6e/source/Controls.hx#L354

**Comment by AbnormalPoof** [comment]
A temporary solution is to hardcode it for now

**Comment by MrClogsworthYT** [comment]
ye

**Comment by DotWith** [comment]
Fixed on experimental branch
